apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nextjs-app
  name: nextjs-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
      - image: ghcr.io/akkimahesh/nextjs-app:latest
        name: nextjs-app
        ports:
          - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/healthcheck
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
