apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: akkimahesh/nextjs-app:latest
          ports:
            - containerPort: 3000
          env:
            # Pass env vars if needed
            # - name: MONGO_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: my-secret
            #       key: mongo-password
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
