apiVersion: v1
kind: Service
metadata:
  name: nextjs-app-service
spec:
  type: NodePort
  selector:
    app: nextjs-app
  ports:
    - protocol: TCP
      port: 3000        # Service port
      targetPort: 3000  # Container port
      nodePort: 30007   # Node port to access via minikube IP
