name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  minikube-job:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker
        run: sudo apt update && sudo apt install -y docker.io

      - name: Add user to Docker group (requires runner restart outside workflow)
        run: sudo usermod -aG docker $USER

      - name: Verify Docker permissions (may fail if group not yet active)
        run: docker version || echo "Docker permission check failed - confirm 'docker' group membership for runner user"

      - name: Start Minikube
        uses: medyagh/setup-minikube@latest
        with:
          minikube-version: '1.34.0'
          driver: 'docker'
          container-runtime: 'containerd'
          kubernetes-version: 'v1.31.0' # Use supported version
          cpus: '2'
          memory: '4000m'
          addons: 'ingress,dashboard'

      - name: Verify Minikube cluster
        run: kubectl get nodes

      - name: Deploy YAML to Minikube
        run: kubectl apply -f k8s/deployment.yaml
