name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build docker image
        run: docker build -t akkimahesh/nextjs-app .
      - name: verify images
        run: docker images
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish image to docker hub
        run: docker push akkimahesh/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: update system
        run: sudo apt update -y
      - name: install Docker
        run: sudo apt install docker.io -y
      - name: docker version check
        run: docker version
      - name: Pull image from docker hub
        run: docker pull akkimahesh/nextjs-app:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container  
      - name: Run docker container
        run: docker run -d --name nextjs-app-container -p 3000:3000 akkimahesh/nextjs-app:latest
