name: Deploy Next.js application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t akkimahesh/nextjs-app:latest .

      - name: Verify images
        run: docker images

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Publish image to Docker Hub
        run: docker push akkimahesh/nextjs-app:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Install Docker
        run: |
         sudo apt-get update -y
         sudo apt-get install -y ca-certificates curl gnupg lsb-release
         sudo mkdir -p /etc/apt/keyrings
         sudo rm -f /etc/apt/keyrings/docker.gpg
         curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor --batch -o /etc/apt/keyrings/docker.gpg
         echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
         $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
         sudo apt-get update -y
         sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

      - name: permission for Docker Sockets
        run: sudo chmod 777 /var/run/docker.sock
      - name: start Docker
        run: sudo systemctl start docker
      - name: Check Docker version
        run: sudo docker version

      - name: Avoid needing sudo for Docker commands
        run: sudo usermod -aG docker ubuntu

      - name: Pull image from Docker Hub
        run: docker pull akkimahesh/nextjs-app:latest

      - name: Delete old container if exists
        run: docker rm -f nextjs-app-container || echo "No existing container to remove"

      - name: Run Docker container
        run: docker run -d --name nextjs-app-container -p 3000:3000 akkimahesh/nextjs-app:latest
        
